//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.09 at 03:44:26 PM COT 
//


package com.swa.challenge.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EventInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TopicCounts" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="TopicName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="TopicCount" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="EventId" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="CreationDatetime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="RequestId" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="TopicName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="TotalEventCount" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="OperationalFlightLegKey">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MarketingFlights">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="MarketingCarrier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="MarketingFlightNumber" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="OperatingCarrier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ScheduledFlightNumber" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="FlightLegInstanceNumber" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="ScheduleDate" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="ScheduledDepartureDatetime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ScheduledArrivalDatetime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ScheduledDepartureStationCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ScheduledArrivalStationCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ArrivalStationCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ScheduledDepartureStationTimeZone" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ScheduledArrivalStationTimeZone" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ArrivalStationTimeZone" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="FlightTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="FlightStateCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ForSale" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="TailNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="NoseNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="EquipmentTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Capacity" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                 &lt;attribute name="SchdDepCentralTzOffset" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="SchdDepStnTzOffset" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="SchdArrCentralTzOffset" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="SchdArrStnTzOffset" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="WifiEquipt" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ScheduledMissionType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ActualMissionType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="OperationType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ScheduledEquipmentTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ScheduledACV" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ACV" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ArrivalGateIdentifier">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="NewGate" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="ArrivalGate" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eventInfo",
    "operationalFlightLegKey",
    "arrivalGateIdentifier"
})
@XmlRootElement(name = "GateAssignment")
public class GateAssignment {

    @XmlElement(name = "EventInfo", required = true)
    protected GateAssignment.EventInfo eventInfo;
    @XmlElement(name = "OperationalFlightLegKey", required = true)
    protected GateAssignment.OperationalFlightLegKey operationalFlightLegKey;
    @XmlElement(name = "ArrivalGateIdentifier", required = true)
    protected GateAssignment.ArrivalGateIdentifier arrivalGateIdentifier;
    @XmlAttribute(name = "ArrivalGate")
    protected Byte arrivalGate;

    /**
     * Gets the value of the eventInfo property.
     * 
     * @return
     *     possible object is
     *     {@link GateAssignment.EventInfo }
     *     
     */
    public GateAssignment.EventInfo getEventInfo() {
        return eventInfo;
    }

    /**
     * Sets the value of the eventInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link GateAssignment.EventInfo }
     *     
     */
    public void setEventInfo(GateAssignment.EventInfo value) {
        this.eventInfo = value;
    }

    /**
     * Gets the value of the operationalFlightLegKey property.
     * 
     * @return
     *     possible object is
     *     {@link GateAssignment.OperationalFlightLegKey }
     *     
     */
    public GateAssignment.OperationalFlightLegKey getOperationalFlightLegKey() {
        return operationalFlightLegKey;
    }

    /**
     * Sets the value of the operationalFlightLegKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link GateAssignment.OperationalFlightLegKey }
     *     
     */
    public void setOperationalFlightLegKey(GateAssignment.OperationalFlightLegKey value) {
        this.operationalFlightLegKey = value;
    }

    /**
     * Gets the value of the arrivalGateIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link GateAssignment.ArrivalGateIdentifier }
     *     
     */
    public GateAssignment.ArrivalGateIdentifier getArrivalGateIdentifier() {
        return arrivalGateIdentifier;
    }

    /**
     * Sets the value of the arrivalGateIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link GateAssignment.ArrivalGateIdentifier }
     *     
     */
    public void setArrivalGateIdentifier(GateAssignment.ArrivalGateIdentifier value) {
        this.arrivalGateIdentifier = value;
    }

    /**
     * Gets the value of the arrivalGate property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getArrivalGate() {
        return arrivalGate;
    }

    /**
     * Sets the value of the arrivalGate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setArrivalGate(Byte value) {
        this.arrivalGate = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="NewGate" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ArrivalGateIdentifier {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "NewGate")
        protected Byte newGate;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the newGate property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getNewGate() {
            return newGate;
        }

        /**
         * Sets the value of the newGate property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setNewGate(Byte value) {
            this.newGate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TopicCounts" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="TopicName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="TopicCount" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="EventId" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="CreationDatetime" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="RequestId" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="TopicName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="TotalEventCount" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "topicCounts"
    })
    public static class EventInfo {

        @XmlElement(name = "TopicCounts")
        protected List<GateAssignment.EventInfo.TopicCounts> topicCounts;
        @XmlAttribute(name = "EventId")
        protected Integer eventId;
        @XmlAttribute(name = "CreationDatetime")
        protected String creationDatetime;
        @XmlAttribute(name = "RequestId")
        protected Integer requestId;
        @XmlAttribute(name = "TopicName")
        protected String topicName;
        @XmlAttribute(name = "TotalEventCount")
        protected Byte totalEventCount;

        /**
         * Gets the value of the topicCounts property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the topicCounts property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTopicCounts().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GateAssignment.EventInfo.TopicCounts }
         * 
         * 
         */
        public List<GateAssignment.EventInfo.TopicCounts> getTopicCounts() {
            if (topicCounts == null) {
                topicCounts = new ArrayList<GateAssignment.EventInfo.TopicCounts>();
            }
            return this.topicCounts;
        }

        /**
         * Gets the value of the eventId property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getEventId() {
            return eventId;
        }

        /**
         * Sets the value of the eventId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setEventId(Integer value) {
            this.eventId = value;
        }

        /**
         * Gets the value of the creationDatetime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCreationDatetime() {
            return creationDatetime;
        }

        /**
         * Sets the value of the creationDatetime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCreationDatetime(String value) {
            this.creationDatetime = value;
        }

        /**
         * Gets the value of the requestId property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getRequestId() {
            return requestId;
        }

        /**
         * Sets the value of the requestId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setRequestId(Integer value) {
            this.requestId = value;
        }

        /**
         * Gets the value of the topicName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTopicName() {
            return topicName;
        }

        /**
         * Sets the value of the topicName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTopicName(String value) {
            this.topicName = value;
        }

        /**
         * Gets the value of the totalEventCount property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getTotalEventCount() {
            return totalEventCount;
        }

        /**
         * Sets the value of the totalEventCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setTotalEventCount(Byte value) {
            this.totalEventCount = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="TopicName" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="TopicCount" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class TopicCounts {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "TopicName")
            protected String topicName;
            @XmlAttribute(name = "TopicCount")
            protected Byte topicCount;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the topicName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTopicName() {
                return topicName;
            }

            /**
             * Sets the value of the topicName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTopicName(String value) {
                this.topicName = value;
            }

            /**
             * Gets the value of the topicCount property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getTopicCount() {
                return topicCount;
            }

            /**
             * Sets the value of the topicCount property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setTopicCount(Byte value) {
                this.topicCount = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MarketingFlights">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="MarketingCarrier" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="MarketingFlightNumber" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="OperatingCarrier" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ScheduledFlightNumber" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="FlightLegInstanceNumber" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="ScheduleDate" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="ScheduledDepartureDatetime" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ScheduledArrivalDatetime" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ScheduledDepartureStationCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ScheduledArrivalStationCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ArrivalStationCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ScheduledDepartureStationTimeZone" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ScheduledArrivalStationTimeZone" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ArrivalStationTimeZone" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="FlightTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="FlightStateCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ForSale" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="TailNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="NoseNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="EquipmentTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Capacity" type="{http://www.w3.org/2001/XMLSchema}short" />
     *       &lt;attribute name="SchdDepCentralTzOffset" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="SchdDepStnTzOffset" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="SchdArrCentralTzOffset" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="SchdArrStnTzOffset" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="WifiEquipt" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ScheduledMissionType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ActualMissionType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="OperationType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ScheduledEquipmentTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ScheduledACV" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ACV" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "marketingFlights"
    })
    public static class OperationalFlightLegKey {

        @XmlElement(name = "MarketingFlights", required = true)
        protected GateAssignment.OperationalFlightLegKey.MarketingFlights marketingFlights;
        @XmlAttribute(name = "OperatingCarrier")
        protected String operatingCarrier;
        @XmlAttribute(name = "ScheduledFlightNumber")
        protected Byte scheduledFlightNumber;
        @XmlAttribute(name = "FlightLegInstanceNumber")
        protected Byte flightLegInstanceNumber;
        @XmlAttribute(name = "ScheduleDate")
        protected Integer scheduleDate;
        @XmlAttribute(name = "ScheduledDepartureDatetime")
        protected String scheduledDepartureDatetime;
        @XmlAttribute(name = "ScheduledArrivalDatetime")
        protected String scheduledArrivalDatetime;
        @XmlAttribute(name = "ScheduledDepartureStationCode")
        protected String scheduledDepartureStationCode;
        @XmlAttribute(name = "ScheduledArrivalStationCode")
        protected String scheduledArrivalStationCode;
        @XmlAttribute(name = "ArrivalStationCode")
        protected String arrivalStationCode;
        @XmlAttribute(name = "ScheduledDepartureStationTimeZone")
        protected String scheduledDepartureStationTimeZone;
        @XmlAttribute(name = "ScheduledArrivalStationTimeZone")
        protected String scheduledArrivalStationTimeZone;
        @XmlAttribute(name = "ArrivalStationTimeZone")
        protected String arrivalStationTimeZone;
        @XmlAttribute(name = "FlightTypeCode")
        protected String flightTypeCode;
        @XmlAttribute(name = "FlightStateCode")
        protected String flightStateCode;
        @XmlAttribute(name = "ForSale")
        protected String forSale;
        @XmlAttribute(name = "TailNumber")
        protected String tailNumber;
        @XmlAttribute(name = "NoseNumber")
        protected String noseNumber;
        @XmlAttribute(name = "EquipmentTypeCode")
        protected String equipmentTypeCode;
        @XmlAttribute(name = "Capacity")
        protected Short capacity;
        @XmlAttribute(name = "SchdDepCentralTzOffset")
        protected Byte schdDepCentralTzOffset;
        @XmlAttribute(name = "SchdDepStnTzOffset")
        protected Byte schdDepStnTzOffset;
        @XmlAttribute(name = "SchdArrCentralTzOffset")
        protected Byte schdArrCentralTzOffset;
        @XmlAttribute(name = "SchdArrStnTzOffset")
        protected Byte schdArrStnTzOffset;
        @XmlAttribute(name = "WifiEquipt")
        protected String wifiEquipt;
        @XmlAttribute(name = "ScheduledMissionType")
        protected String scheduledMissionType;
        @XmlAttribute(name = "ActualMissionType")
        protected String actualMissionType;
        @XmlAttribute(name = "OperationType")
        protected String operationType;
        @XmlAttribute(name = "ScheduledEquipmentTypeCode")
        protected String scheduledEquipmentTypeCode;
        @XmlAttribute(name = "ScheduledACV")
        protected String scheduledACV;
        @XmlAttribute(name = "ACV")
        protected String acv;

        /**
         * Gets the value of the marketingFlights property.
         * 
         * @return
         *     possible object is
         *     {@link GateAssignment.OperationalFlightLegKey.MarketingFlights }
         *     
         */
        public GateAssignment.OperationalFlightLegKey.MarketingFlights getMarketingFlights() {
            return marketingFlights;
        }

        /**
         * Sets the value of the marketingFlights property.
         * 
         * @param value
         *     allowed object is
         *     {@link GateAssignment.OperationalFlightLegKey.MarketingFlights }
         *     
         */
        public void setMarketingFlights(GateAssignment.OperationalFlightLegKey.MarketingFlights value) {
            this.marketingFlights = value;
        }

        /**
         * Gets the value of the operatingCarrier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOperatingCarrier() {
            return operatingCarrier;
        }

        /**
         * Sets the value of the operatingCarrier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOperatingCarrier(String value) {
            this.operatingCarrier = value;
        }

        /**
         * Gets the value of the scheduledFlightNumber property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getScheduledFlightNumber() {
            return scheduledFlightNumber;
        }

        /**
         * Sets the value of the scheduledFlightNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setScheduledFlightNumber(Byte value) {
            this.scheduledFlightNumber = value;
        }

        /**
         * Gets the value of the flightLegInstanceNumber property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getFlightLegInstanceNumber() {
            return flightLegInstanceNumber;
        }

        /**
         * Sets the value of the flightLegInstanceNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setFlightLegInstanceNumber(Byte value) {
            this.flightLegInstanceNumber = value;
        }

        /**
         * Gets the value of the scheduleDate property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getScheduleDate() {
            return scheduleDate;
        }

        /**
         * Sets the value of the scheduleDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setScheduleDate(Integer value) {
            this.scheduleDate = value;
        }

        /**
         * Gets the value of the scheduledDepartureDatetime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScheduledDepartureDatetime() {
            return scheduledDepartureDatetime;
        }

        /**
         * Sets the value of the scheduledDepartureDatetime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScheduledDepartureDatetime(String value) {
            this.scheduledDepartureDatetime = value;
        }

        /**
         * Gets the value of the scheduledArrivalDatetime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScheduledArrivalDatetime() {
            return scheduledArrivalDatetime;
        }

        /**
         * Sets the value of the scheduledArrivalDatetime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScheduledArrivalDatetime(String value) {
            this.scheduledArrivalDatetime = value;
        }

        /**
         * Gets the value of the scheduledDepartureStationCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScheduledDepartureStationCode() {
            return scheduledDepartureStationCode;
        }

        /**
         * Sets the value of the scheduledDepartureStationCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScheduledDepartureStationCode(String value) {
            this.scheduledDepartureStationCode = value;
        }

        /**
         * Gets the value of the scheduledArrivalStationCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScheduledArrivalStationCode() {
            return scheduledArrivalStationCode;
        }

        /**
         * Sets the value of the scheduledArrivalStationCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScheduledArrivalStationCode(String value) {
            this.scheduledArrivalStationCode = value;
        }

        /**
         * Gets the value of the arrivalStationCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getArrivalStationCode() {
            return arrivalStationCode;
        }

        /**
         * Sets the value of the arrivalStationCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setArrivalStationCode(String value) {
            this.arrivalStationCode = value;
        }

        /**
         * Gets the value of the scheduledDepartureStationTimeZone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScheduledDepartureStationTimeZone() {
            return scheduledDepartureStationTimeZone;
        }

        /**
         * Sets the value of the scheduledDepartureStationTimeZone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScheduledDepartureStationTimeZone(String value) {
            this.scheduledDepartureStationTimeZone = value;
        }

        /**
         * Gets the value of the scheduledArrivalStationTimeZone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScheduledArrivalStationTimeZone() {
            return scheduledArrivalStationTimeZone;
        }

        /**
         * Sets the value of the scheduledArrivalStationTimeZone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScheduledArrivalStationTimeZone(String value) {
            this.scheduledArrivalStationTimeZone = value;
        }

        /**
         * Gets the value of the arrivalStationTimeZone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getArrivalStationTimeZone() {
            return arrivalStationTimeZone;
        }

        /**
         * Sets the value of the arrivalStationTimeZone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setArrivalStationTimeZone(String value) {
            this.arrivalStationTimeZone = value;
        }

        /**
         * Gets the value of the flightTypeCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFlightTypeCode() {
            return flightTypeCode;
        }

        /**
         * Sets the value of the flightTypeCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFlightTypeCode(String value) {
            this.flightTypeCode = value;
        }

        /**
         * Gets the value of the flightStateCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFlightStateCode() {
            return flightStateCode;
        }

        /**
         * Sets the value of the flightStateCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFlightStateCode(String value) {
            this.flightStateCode = value;
        }

        /**
         * Gets the value of the forSale property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getForSale() {
            return forSale;
        }

        /**
         * Sets the value of the forSale property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setForSale(String value) {
            this.forSale = value;
        }

        /**
         * Gets the value of the tailNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTailNumber() {
            return tailNumber;
        }

        /**
         * Sets the value of the tailNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTailNumber(String value) {
            this.tailNumber = value;
        }

        /**
         * Gets the value of the noseNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNoseNumber() {
            return noseNumber;
        }

        /**
         * Sets the value of the noseNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNoseNumber(String value) {
            this.noseNumber = value;
        }

        /**
         * Gets the value of the equipmentTypeCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEquipmentTypeCode() {
            return equipmentTypeCode;
        }

        /**
         * Sets the value of the equipmentTypeCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEquipmentTypeCode(String value) {
            this.equipmentTypeCode = value;
        }

        /**
         * Gets the value of the capacity property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getCapacity() {
            return capacity;
        }

        /**
         * Sets the value of the capacity property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setCapacity(Short value) {
            this.capacity = value;
        }

        /**
         * Gets the value of the schdDepCentralTzOffset property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getSchdDepCentralTzOffset() {
            return schdDepCentralTzOffset;
        }

        /**
         * Sets the value of the schdDepCentralTzOffset property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setSchdDepCentralTzOffset(Byte value) {
            this.schdDepCentralTzOffset = value;
        }

        /**
         * Gets the value of the schdDepStnTzOffset property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getSchdDepStnTzOffset() {
            return schdDepStnTzOffset;
        }

        /**
         * Sets the value of the schdDepStnTzOffset property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setSchdDepStnTzOffset(Byte value) {
            this.schdDepStnTzOffset = value;
        }

        /**
         * Gets the value of the schdArrCentralTzOffset property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getSchdArrCentralTzOffset() {
            return schdArrCentralTzOffset;
        }

        /**
         * Sets the value of the schdArrCentralTzOffset property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setSchdArrCentralTzOffset(Byte value) {
            this.schdArrCentralTzOffset = value;
        }

        /**
         * Gets the value of the schdArrStnTzOffset property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getSchdArrStnTzOffset() {
            return schdArrStnTzOffset;
        }

        /**
         * Sets the value of the schdArrStnTzOffset property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setSchdArrStnTzOffset(Byte value) {
            this.schdArrStnTzOffset = value;
        }

        /**
         * Gets the value of the wifiEquipt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWifiEquipt() {
            return wifiEquipt;
        }

        /**
         * Sets the value of the wifiEquipt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWifiEquipt(String value) {
            this.wifiEquipt = value;
        }

        /**
         * Gets the value of the scheduledMissionType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScheduledMissionType() {
            return scheduledMissionType;
        }

        /**
         * Sets the value of the scheduledMissionType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScheduledMissionType(String value) {
            this.scheduledMissionType = value;
        }

        /**
         * Gets the value of the actualMissionType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActualMissionType() {
            return actualMissionType;
        }

        /**
         * Sets the value of the actualMissionType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActualMissionType(String value) {
            this.actualMissionType = value;
        }

        /**
         * Gets the value of the operationType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOperationType() {
            return operationType;
        }

        /**
         * Sets the value of the operationType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOperationType(String value) {
            this.operationType = value;
        }

        /**
         * Gets the value of the scheduledEquipmentTypeCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScheduledEquipmentTypeCode() {
            return scheduledEquipmentTypeCode;
        }

        /**
         * Sets the value of the scheduledEquipmentTypeCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScheduledEquipmentTypeCode(String value) {
            this.scheduledEquipmentTypeCode = value;
        }

        /**
         * Gets the value of the scheduledACV property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScheduledACV() {
            return scheduledACV;
        }

        /**
         * Sets the value of the scheduledACV property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScheduledACV(String value) {
            this.scheduledACV = value;
        }

        /**
         * Gets the value of the acv property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getACV() {
            return acv;
        }

        /**
         * Sets the value of the acv property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setACV(String value) {
            this.acv = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="MarketingCarrier" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="MarketingFlightNumber" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class MarketingFlights {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "MarketingCarrier")
            protected String marketingCarrier;
            @XmlAttribute(name = "MarketingFlightNumber")
            protected Byte marketingFlightNumber;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the marketingCarrier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMarketingCarrier() {
                return marketingCarrier;
            }

            /**
             * Sets the value of the marketingCarrier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMarketingCarrier(String value) {
                this.marketingCarrier = value;
            }

            /**
             * Gets the value of the marketingFlightNumber property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getMarketingFlightNumber() {
                return marketingFlightNumber;
            }

            /**
             * Sets the value of the marketingFlightNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setMarketingFlightNumber(Byte value) {
                this.marketingFlightNumber = value;
            }

        }

    }

}
